# @package _group_
env: "intersection-v0"
logging:
  wandb: false
  project_name: 'Highway_env'
  tensorboard_log: 'logs'


env_args:
  _target_: mbrl.planning.TrajectoryOptimizerAgent
  offroad_terminal: true
  destination: 'o1'
  initial_vehicle_count: 0
  spawn_probability: 0
  collision_reward: -10
  on_road_reward: 1 
  path_reward: 0
  arrived_reward: 10
  simulation_frequency: 10
  policy_frequency: 5
  # ego_lane: [
  #           ["o2", "ir2", 0],
  #           ["o1", "ir1", 0]
  #         ]
  observation:
    type: TupleObservation
    observation_configs:
      - type: GrayscaleObservation
        observation_shape: [128, 128]
        stack_size: 4
        weights: [0.2989, 0.5870, 0.1140] 
        scaling: 1.75

      - type: Kinematics
        features:
          - presence
          - x
          - y
          - vx
          - vy
          - lane_id
          - heading
        absolute: false
        features_range: 
            x: [0, 0]
            y: [0, 0]
            vx: [-20, 20]
            vy: [-20, 20]
        
  action: 
    type: ContinuousAction

term_fn: "no_termination"

# General configuration overrides
trial_length: 100
action_noise_std: 0.3

# Model overrides
num_grad_updates: 100
sequence_length: 30
batch_size: 20
free_nats: 3
kl_scale: 1.0

# Planner configuration overrides
planning_horizon: 30
mppi_num_iters: 5
mppi_population_size: 350
mppi_gamma: 0.9
mppi_sigma: 1.0
mppi_beta: 0.9
# planning_horizon: 12
# cem_num_iters: 10
# cem_elite_ratio: 0.1
# cem_population_size: 1000
# cem_alpha: 0.0
# cem_clipped_normal: true

mppi:
  nx : 4
  noise_sigma: [[5, 0],[0,0.7]]
  noise_mu : [0, 0]
  u_min: [-5, -0.7]
  u_max: [5, 0.5]
  horizon: 15 
  num_samples : 500
  lambda_: 2000


