# @package _group_
_target_: mbrl.models.PlaNetModel
obs_shape: [3, 128, 128]
obs_encoding_size: 9216 #256 * 6 * 6 
vec_input: 5
encoder_config:
  - [3, 32, 4, 2] #[in_channels, out_channels, kernel_size, stride]
  - [32, 64, 4, 2]
  - [64, 128, 4, 2]
  - [128, 256, 4, 2]
decoder_config:
  - [1024, 1, 1] #deconv_input_shape
  - - [1024, 128, 5, 2] #deconv_layers_config
    - [128, 64, 5, 2]
    - [64, 32, 6, 2]
    - [32, 4, 6, 2]
    - [4,3, 2, 2]
action_size: ???
hidden_size_fcs: 200
belief_size: 200
latent_state_size: 30
device: ${device}
min_std: 0.1
free_nats: 3.0
kl_scale: 1.0
grad_clip_norm: 1000.0
